/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.d_alquileres_anda;
import dominio.d_inquilino;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author gonza
 */
public class p_listado_inq_anda extends javax.swing.JDialog {

    DefaultTableModel mdltabinq = new DefaultTableModel();
    List<d_alquileres_anda> lista = new ArrayList<>();
    TableRowSorter trs;
    /**
     * Creates new form p_agregar_inq_anda
     */
    public p_listado_inq_anda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        tblinquilinos.setModel(mdltabinq);

        mdltabinq.addColumn("ID PROP");
        mdltabinq.addColumn("ID INQ");
        mdltabinq.addColumn("ID ANDA");
        mdltabinq.addColumn("NOMBRE");
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblinquilinos = tblinquilinos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        txtfiltro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTADO DE REGISTROS EXCEL INGRESADOS");
        getContentPane().setLayout(null);

        tblinquilinos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tblinquilinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinquilinosMouseClicked(evt);
            }
        });
        tblinquilinos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblinquilinosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblinquilinos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 570, 140);

        txtfiltro.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtfiltro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtfiltroAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfiltroActionPerformed(evt);
            }
        });
        txtfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfiltroKeyTyped(evt);
            }
        });
        getContentPane().add(txtfiltro);
        txtfiltro.setBounds(10, 30, 270, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("FILTRO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 260, 17);

        setBounds(0, 0, 607, 269);
    }// </editor-fold>//GEN-END:initComponents

    private void tblinquilinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinquilinosMouseClicked
        int prop_id;
        int inq_casa;
        String nombre;
        try {
            int rows[] = tblinquilinos.getSelectedRows();
            int row = -1;

            for (int i = 0; i < rows.length; i++) {
                row = rows[i];
            }

            prop_id = Integer.parseInt(tblinquilinos.getValueAt(row, 0).toString());
            inq_casa = Integer.parseInt(tblinquilinos.getValueAt(row, 1).toString());
            nombre = ((String) tblinquilinos.getValueAt(row, 3));
            if (evt.getClickCount() == 2) {
                //doble clic
                int ax = JOptionPane.showConfirmDialog(null, toUpperCase("¿desea eliminar a: " + prop_id + " - " + inq_casa + "\n" + nombre + "?"), "CONFIRMACION", JOptionPane.YES_NO_CANCEL_OPTION);
                if (ax == JOptionPane.NO_OPTION) {
                    return;
                }
                if (ax == JOptionPane.CANCEL_OPTION) {
                    return;
                }
                if (ax == JOptionPane.YES_OPTION) {
                    d_alquileres_anda alq = new d_alquileres_anda();
                    alq.eliminar_alquiler_anda(prop_id, inq_casa);
                    JOptionPane.showMessageDialog(this, "REGISTRO ELIMINADO CORRECTAMENTE", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                    cargar();
                }
            }
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblinquilinosMouseClicked

    private void tblinquilinosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblinquilinosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblinquilinosKeyPressed

    private void txtfiltroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtfiltroAncestorAdded
        txtfiltro.requestFocus();
    }//GEN-LAST:event_txtfiltroAncestorAdded

    private void txtfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiltroActionPerformed

    private void txtfiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfiltroKeyTyped
        txtfiltro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                super.keyReleased(e); //To change body of generated methods, choose Tools | Templates.
                trs.setRowFilter(RowFilter.regexFilter("^" + txtfiltro.getText().toUpperCase(), 3));
            }
        });
        trs = new TableRowSorter(mdltabinq);
        tblinquilinos.setRowSorter(trs);
    }//GEN-LAST:event_txtfiltroKeyTyped

    void cargar() {
        d_alquileres_anda inq = new d_alquileres_anda();
        d_alquileres_anda inq1 = null;
        d_inquilino x = new d_inquilino();
        Vector v;
        String id_anda;

        try {
            cleartable();
            lista = inq.listar_alquileres_anda();
            for (d_alquileres_anda aux : lista) {
                inq1 = new d_alquileres_anda();
                v = new Vector();
                inq1.setProp_id(aux.getProp_id());
                inq1.setInq_casa(aux.getInq_casa());     
                id_anda=aux.getId_anda();
                inq1.setId_anda(x.buscarnombreinquilino(aux.getProp_id(), aux.getInq_casa()));                
                v.add(inq1.getProp_id());
                v.add(inq1.getInq_casa());
                v.add(id_anda);
                v.add(inq1.getId_anda());
                mdltabinq.addRow(v);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    void cleartable() {
        for (int i = 0; i < tblinquilinos.getRowCount(); i++) {
            mdltabinq.removeRow(i);
            i -= 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_listado_inq_anda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_listado_inq_anda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_listado_inq_anda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_listado_inq_anda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                p_listado_inq_anda dialog = new p_listado_inq_anda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblinquilinos;
    private javax.swing.JTextField txtfiltro;
    // End of variables declaration//GEN-END:variables
}
