/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.d_inquilino;
import interfaces.observador_inq;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import persistencia.p_conexion;
import presentacion.paneles.p_control;
import presentacion.paneles.p_fichainquilino;

/**
 *
 * @author Gonzalo
 */
public class p_lstinquilinos extends javax.swing.JFrame implements observador_inq {
    
    DefaultTableModel mdltabinq = new DefaultTableModel();
    List<d_inquilino> listainquilinos = new ArrayList<d_inquilino>();
    TableRowSorter trs;
    
    public p_lstinquilinos() {
        initComponents();
        setLocationRelativeTo(null);
        
        tblinquilinos.setModel(mdltabinq);
        
        mdltabinq.addColumn("ID PROP");
        mdltabinq.addColumn("ID INQ");
        mdltabinq.addColumn("NOMBRE");
        mdltabinq.addColumn("DIRECCION");
        mdltabinq.addColumn("NRO CONTACTO");
        mdltabinq.addColumn("OBSERVACIONES");
        
        cargarinquilinos();
        cargarobservador();
    }
    
    void cargarobservador() {
        p_control con = p_control.getInstancia();
        con.registrarobservador_inq(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblinquilinos = tblinquilinos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        btnexportar = new javax.swing.JButton();
        cmbordenar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtfiltro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTA DE INQUILINOS");
        getContentPane().setLayout(null);

        tblinquilinos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tblinquilinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinquilinosMouseClicked(evt);
            }
        });
        tblinquilinos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblinquilinosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblinquilinos);
        if (tblinquilinos.getColumnModel().getColumnCount() > 0) {
            tblinquilinos.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tblinquilinos.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tblinquilinos.getColumnModel().getColumn(2).setHeaderValue("null");
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 952, 410);

        btnexportar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnexportar.setText("EXPORTAR");
        btnexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnexportar);
        btnexportar.setBounds(10, 500, 120, 30);

        cmbordenar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cmbordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOMBRE", "DIRECCION" }));
        cmbordenar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbordenarKeyPressed(evt);
            }
        });
        getContentPane().add(cmbordenar);
        cmbordenar.setBounds(10, 40, 138, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 40, 120, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("FILTRO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 20, 260, 17);

        txtfiltro.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtfiltro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtfiltroAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfiltroActionPerformed(evt);
            }
        });
        txtfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfiltroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfiltroKeyTyped(evt);
            }
        });
        getContentPane().add(txtfiltro);
        txtfiltro.setBounds(170, 40, 270, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("ORDEN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 50, 17);

        setBounds(0, 0, 1012, 578);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportarActionPerformed
        try {
            java.sql.Connection c;
            p_conexion conex = p_conexion.getInstancia();
            c = conex.crearconexion();
            //javax.swing.JOptionPane.showMessageDialog(null, "Conexion establecida");

            String template = "report-4.jasper";
            JasperReport reporte = null;
            reporte = (JasperReport) JRLoader.loadObject(template);

            //Map param = new HashMap();
            //param.put("id", 1);
            JasperPrint jasperprint = JasperFillManager.fillReport(reporte, null, c);
            //donde dice 'null' va el parametro, si es utilizado
            JasperViewer visor = new JasperViewer(jasperprint, false);
            visor.setTitle("Lista de Inquilinos");
            visor.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, toUpperCase(e), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnexportarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        funcbuscar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    void funcbuscar() {
        d_inquilino inq = new d_inquilino();
        d_inquilino inq1 = null;
        Vector v;
        
        try {
            if (cmbordenar.getSelectedItem().equals("ID")) {
                listainquilinos = inq.listarinquilinos();
            }
            if (cmbordenar.getSelectedItem().equals("NOMBRE")) {
                listainquilinos = inq.listarinquilinospornombre();
            }
            if (cmbordenar.getSelectedItem().equals("DIRECCION")) {
                listainquilinos = inq.listarinquilinospordireccion();
            }
            cleartable();
            for (d_inquilino aux : listainquilinos) {
                
                inq1 = new d_inquilino();
                v = new Vector();
                inq1.setProp_id(aux.getProp_id());
                inq1.setInq_casa(aux.getInq_casa());
                inq1.setInq_nombre(aux.getInq_nombre());
                inq1.setInq_direccion(aux.getInq_direccion());
                inq1.setInq_tel(aux.getInq_tel());
                inq1.setInq_observaciones(aux.getInq_observaciones());
                v.add(inq1.getProp_id());
                v.add(inq1.getInq_casa());
                v.add(inq1.getInq_nombre());
                v.add(inq1.getInq_direccion());
                v.add(inq1.getInq_tel());
                v.add(inq1.getInq_observaciones());
                mdltabinq.addRow(v);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tblinquilinosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblinquilinosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblinquilinosKeyPressed

    private void tblinquilinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinquilinosMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                selecciontabla();
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblinquilinosMouseClicked

    private void cmbordenarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbordenarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            funcbuscar();
        }
    }//GEN-LAST:event_cmbordenarKeyPressed

    private void txtfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiltroActionPerformed

    private void txtfiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfiltroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            funcbuscar();
        }
    }//GEN-LAST:event_txtfiltroKeyPressed

    private void txtfiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfiltroKeyTyped
        txtfiltro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                super.keyReleased(e); //To change body of generated methods, choose Tools | Templates.                
                trs.setRowFilter(RowFilter.regexFilter("^"+txtfiltro.getText().toUpperCase(), 2));
            }            
        });
        trs = new TableRowSorter(mdltabinq);
        tblinquilinos.setRowSorter(trs);
    }//GEN-LAST:event_txtfiltroKeyTyped

    private void txtfiltroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtfiltroAncestorAdded
        txtfiltro.requestFocus();
    }//GEN-LAST:event_txtfiltroAncestorAdded
    
    void cleartable() {
        for (int i = 0; i < tblinquilinos.getRowCount(); i++) {
            mdltabinq.removeRow(i);
            i -= 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_lstinquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_lstinquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_lstinquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_lstinquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p_lstinquilinos().setVisible(true);
            }
        });
    }
    
    void cargarinquilinos() {
        d_inquilino inq = new d_inquilino();
        d_inquilino inq1 = null;
        Vector v;
        
        try {
            cleartable();
            listainquilinos = inq.listarinquilinos();
            for (d_inquilino aux : listainquilinos) {
                inq1 = new d_inquilino();
                v = new Vector();
                inq1.setProp_id(aux.getProp_id());
                inq1.setInq_casa(aux.getInq_casa());
                inq1.setInq_nombre(aux.getInq_nombre());
                inq1.setInq_direccion(aux.getInq_direccion());
                inq1.setInq_tel(aux.getInq_tel());
                inq1.setInq_observaciones(aux.getInq_observaciones());
                v.add(inq1.getProp_id());
                v.add(inq1.getInq_casa());
                v.add(inq1.getInq_nombre());
                v.add(inq1.getInq_direccion());
                v.add(inq1.getInq_tel());
                v.add(inq1.getInq_observaciones());
                mdltabinq.addRow(v);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void selecciontabla() throws Exception {
        p_fichainquilino fic = null;
        p_control con = p_control.getInstancia();
        
        int row = tblinquilinos.getSelectedRow(); //guarda el numero de fila que selecciona el usuario

        if (row != -1) {
            d_inquilino inq = new d_inquilino();
            inq.setProp_id((Integer) tblinquilinos.getValueAt(row, 0));
            inq.setInq_casa((Integer) tblinquilinos.getValueAt(row, 1));
            inq.setInq_nombre((String) tblinquilinos.getValueAt(row, 2));
            inq.setInq_direccion((String) tblinquilinos.getValueAt(row, 3));
            inq.setInq_tel((Integer) tblinquilinos.getValueAt(row, 4));
            inq.setInq_observaciones((String) tblinquilinos.getValueAt(row, 5));
            inq = inq.buscarinquilino(inq.getProp_id(), inq.getInq_casa());
            con.inq = inq;
            fic = new p_fichainquilino(new JDialog(), true);
            fic.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, toUpperCase("debe seleccionar una fila"), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexportar;
    private javax.swing.JComboBox<String> cmbordenar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblinquilinos;
    private javax.swing.JTextField txtfiltro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        cargarinquilinos();
    }
}
