/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.paneles;

import dominio.d_propietario;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import persistencia.p_conexion;

/**
 *
 * @author Gonzalo
 */
public class listadosobregiros extends javax.swing.JDialog {

    DefaultTableModel mdltabpro = new DefaultTableModel();
    List<d_propietario> listapropietarios = new ArrayList<d_propietario>();

    /**
     * Creates new form listadosmora1
     */
    public listadosobregiros(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        p_control c = p_control.getInstancia();
        tblpropietarios.setModel(mdltabpro);

        mdltabpro.addColumn("ID PROP");
        mdltabpro.addColumn("NOMBRE");
        mdltabpro.addColumn("SALDO");
        c.alinear_contenido_columna_izquierda(tblpropietarios, 2);
        cargarsobregiros();
    }

    void cargarsobregiros() {
        p_control con = p_control.getInstancia();
        d_propietario prop = new d_propietario();
        d_propietario prop1 = null;
        Float saldototal = 0f;
        Vector v;

        try {

            listapropietarios = prop.listarsobregirospropietarios();
            for (d_propietario aux : listapropietarios) {
                if (aux.getProp_id() == 0) {
                    continue;
                }
                prop1 = new d_propietario();
                v = new Vector();
                prop1.setProp_id(aux.getProp_id());
                prop1.setProp_nombre(aux.getProp_nombre());
                prop1.setProp_saldo(aux.getProp_saldo());
                v.add(prop1.getProp_id());
                v.add(prop1.getProp_nombre());
                v.add(con.mostrarnumero(prop1.getProp_saldo()));
                saldototal = saldototal + prop1.getProp_saldo();
                mdltabpro.addRow(v);
            }
            lblsaldo.setText(con.mostrarnumero(saldototal));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblpropietarios = tblpropietarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel1 = new javax.swing.JLabel();
        lblsaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SOBREGIROS DE PROPIETARIOS");
        setModalityType(null);
        getContentPane().setLayout(null);

        tblpropietarios.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tblpropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpropietariosMouseClicked(evt);
            }
        });
        tblpropietarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblpropietariosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblpropietarios);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 566, 237);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("SALDO TOTAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 270, 230, 17);

        lblsaldo.setBackground(java.awt.Color.green);
        lblsaldo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblsaldo.setOpaque(true);
        getContentPane().add(lblsaldo);
        lblsaldo.setBounds(10, 290, 400, 30);

        jButton1.setText("EXPORTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 340, 120, 30);

        setBounds(0, 0, 626, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void tblpropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpropietariosMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                selecciontabla();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblpropietariosMouseClicked

    private void tblpropietariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblpropietariosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpropietariosKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            java.sql.Connection c;
            p_conexion conex = p_conexion.getInstancia();
            c = conex.crearconexion();

            String template = "report-sobregirosprop.jasper";
            JasperReport reporte = null;
            reporte = (JasperReport) JRLoader.loadObject(template);

            //Map param = new HashMap();
            //param.put("id", 1);
            JasperPrint jasperprint = JasperFillManager.fillReport(reporte, null, c);
            //donde dice 'null' va el parametro, si es utilizado
            //this.setVisible(false);
            JasperViewer visor = new JasperViewer(jasperprint, false);
            visor.setTitle("Lista de Propietarios con sobregiros");
            visor.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, toUpperCase(e), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    void selecciontabla() throws Exception {
        p_fichapropietario fip = null;
        p_control con = p_control.getInstancia();

        int row = tblpropietarios.getSelectedRow(); //guarda el numero de fila que selecciona el usuario

        if (row != -1) {
            d_propietario prop = new d_propietario();
            //datoseleccionado += tblmodelos.getValueAt(row, 2); //guarda el valor que hay en la columna idoperario
            //idpieza = Integer.parseInt(datoseleccionado); //convierte a Integer
            prop.setProp_id((Integer) tblpropietarios.getValueAt(row, 0));
            prop.setProp_nombre((String) tblpropietarios.getValueAt(row, 1));
            //prop.setProp_saldo((Float) tblpropietarios.getValueAt(row, 2));
            con.prop = prop;
            fip = new p_fichapropietario(null, true);
            fip.setVisible(true);
            //con.cargarpropietario(pro);
            //notificarseleccion(); 
        } else {
            JOptionPane.showMessageDialog(null, toUpperCase("debe seleccionar una fila"), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listadosobregiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listadosobregiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listadosobregiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listadosobregiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                listadosobregiros dialog = new listadosobregiros(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblsaldo;
    private javax.swing.JTable tblpropietarios;
    // End of variables declaration//GEN-END:variables
}
