/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.paneles;

import dominio.d_clave;
import interfaces.observador_prop;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author Gonzalo
 */
public class p_cambioclave extends javax.swing.JDialog implements observador_prop {

    Integer accion = 1;

    /**
     * Creates new form p_fichainquilino
     */
    public p_cambioclave(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        txtrepetirclave = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        txtnuevaclave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAMBIO DE CLAVE");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("NUEVA CLAVE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 120, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("REPETIR CLAVE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 120, 120, 17);

        btnactualizar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar);
        btnactualizar.setBounds(180, 40, 120, 30);
        getContentPane().add(txtrepetirclave);
        txtrepetirclave.setBounds(10, 140, 138, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("CLAVE");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 20, 70, 17);
        getContentPane().add(txtclave);
        txtclave.setBounds(10, 40, 138, 30);
        getContentPane().add(txtnuevaclave);
        txtnuevaclave.setBounds(10, 90, 138, 30);

        setBounds(0, 0, 325, 221);
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        d_clave cla = new d_clave();

        //accion 1 guarda, accion 2 cierra
        try {
            if (accion == 1) {
                controlarclave();
                controlarcampos();
                cla.setClave(txtnuevaclave.getText());
                cla.actualizarclave(cla);
                JOptionPane.showMessageDialog(this, "CLAVE ACTUALIZADA CORRECTAMENTE", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                btnactualizar.setText("CERRAR");
                accion = 2;    
                return;
            }
            if (accion == 2) {
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    void controlarclave() throws Exception {
        d_clave cla = new d_clave();

        cla = cla.buscarclave();

        if (!txtclave.getText().equals(cla.getClave())) {
            throw new Exception("clave incorrecta");
        }
    }

    void controlarcampos() throws Exception {
        if (txtnuevaclave.getText().equals("") || txtrepetirclave.getText().equals("")) {
            throw new Exception("no puede quedar un campo vacio");
        }
        if (!txtnuevaclave.getText().equals(txtrepetirclave.getText())) {
            throw new Exception("no coinciden las claves ingresadas");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_cambioclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_cambioclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_cambioclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_cambioclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                p_cambioclave dialog = new p_cambioclave(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JPasswordField txtnuevaclave;
    private javax.swing.JPasswordField txtrepetirclave;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        p_control con = p_control.getInstancia();

        con.actualizar_prop();
    }
}
