/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.paneles;

import dominio.d_caja;
import dominio.d_movimiento;
import dominio.d_propietario;
import java.io.Serializable;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author Gonzalo
 */
public class p_caja extends javax.swing.JDialog implements Serializable {
float montototal = 0f;
    /**
     * Creates new form p_fichainquilino
     */
    public p_caja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        cargarfecha();
        cargardatoscaja();
        cargardatoscajabdd();
    }

    void cargarfecha() {
        jdcfecha.setDate(new Date());
    }

    void cargardatoscaja() {
        p_control con = p_control.getInstancia();
        d_caja caja = null;
        d_caja aux = new d_caja();
        Float cajainicial = 0f;
        Float entrada = 0f;
        Float salida = 0f;
        Float total = 0f;

        try {
            cajainicial = 0f;
            caja = aux.buscarcaja();
            if (caja != null) {
                cajainicial = caja.getMonto();
            }
            entrada = totalentradatipopagohoy();
            salida = totalsalidatipopagohoy();
            txtcajainicial.setText(con.mostrarnumero(cajainicial));
            txtentrada.setText(con.mostrarnumero(entrada));
            txtsalida.setText(con.mostrarnumero(salida));
            txtvalor.setText("0");
            total = devuelvemontototal();
            txttotal.setText(con.mostrarnumero(total));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    void cargardatoscajabdd() {
        p_control con = p_control.getInstancia();
        d_caja caja = null;
        d_caja aux = new d_caja();
        float sindatos = 0f;

        try {
            caja = aux.buscarcaja();
            if (caja == null) {
                lbldatoscaja.setText(con.mostrarnumero(sindatos) + " CAJA NO INICIADA");
            } else {
                String fecha = parsefechastring(caja.getFecha());
                lbldatoscaja.setText("$: " + con.mostrarnumero(caja.getMonto()) + " " + "FECHA: " + fecha);
                txtcajainicial.setText(con.mostrarnumero(caja.getMonto()));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtsalida = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jdcfecha = new com.toedter.calendar.JDateChooser();
        txtentrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcajainicial = new javax.swing.JTextField();
        lbldatoscaja = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MANTENIMIENTO CAJA");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("ENTRADA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 80, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("SALIDA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 90, 17);

        txtsalida.setEditable(false);
        txtsalida.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        getContentPane().add(txtsalida);
        txtsalida.setBounds(10, 190, 138, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("CONFIRMA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 240, 120, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("FECHA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 20, 100, 17);

        jdcfecha.setEnabled(false);
        jdcfecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jdcfecha);
        jdcfecha.setBounds(190, 40, 138, 30);

        txtentrada.setEditable(false);
        txtentrada.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        getContentPane().add(txtentrada);
        txtentrada.setBounds(10, 140, 138, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("CAJA INICIAL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 20, 100, 17);

        txtcajainicial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtcajainicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcajainicialFocusLost(evt);
            }
        });
        txtcajainicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcajainicialKeyPressed(evt);
            }
        });
        getContentPane().add(txtcajainicial);
        txtcajainicial.setBounds(10, 40, 138, 30);

        lbldatoscaja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldatoscaja.setForeground(java.awt.Color.red);
        lbldatoscaja.setText("NO HAY DATOS GUARDADOS");
        getContentPane().add(lbldatoscaja);
        lbldatoscaja.setBounds(10, 300, 320, 17);

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        getContentPane().add(txttotal);
        txttotal.setBounds(10, 240, 138, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 220, 90, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("ULTIMA ACTUALIZACIÓN:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 280, 320, 17);

        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setText("CALCULAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 90, 120, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("AGREGAR VALOR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 70, 130, 17);

        txtvalor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        getContentPane().add(txtvalor);
        txtvalor.setBounds(10, 90, 138, 30);

        setBounds(0, 0, 352, 372);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        p_control con = p_control.getInstancia();
        d_caja caja = new d_caja();
        float montototal = 0f;

        try {
            int ax = JOptionPane.showConfirmDialog(null,
                    "¿DESEA ACTUALIZAR EL MONTO A: " + txttotal.getText() + "?", "CONFIRMACION", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ax == JOptionPane.YES_OPTION) {
                //mov.guardarmovimientogastoinmo(mov);
                //JOptionPane.showMessageDialog(this, "MOVIMIENTO GUARDADO CORRECTAMENTE", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                caja.setFecha(new Timestamp(System.currentTimeMillis()));

                montototal = devuelvemontototal();

                caja.setMonto(montototal);
                caja.actualizarcaja(caja);
                
                con.escribirfichero("INMO - se actualiza caja, fecha: " + parsefechastring(caja.getFecha()) + " -- " + "monto: " + con.mostrarnumero(caja.getMonto()));
                
                JOptionPane.showMessageDialog(this, "DATOS ACTUALIZADOS CORRECTAMENTE", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                //cargarfecha();
                //cargardatoscaja();
                //cargardatoscajabdd();
                this.dispose();
            } else {
                cargarfecha();
                cargardatoscaja();
                cargardatoscajabdd();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    float devuelvemontototal() throws Exception {
        p_control con = p_control.getInstancia();
        float cajainicial = 0f;
        float valor = 0f;
        //float montototal = 0f;

        if (txtcajainicial.getText().isEmpty()) {
            cajainicial = 0f;
        } else {
            cajainicial = con.guardarnumero((txtcajainicial.getText()));
        }
        
        if (txtvalor.getText().isEmpty()) {
            valor = 0f;
        } else {
            valor = con.guardarnumero((txtvalor.getText()));
        }
        montototal = (cajainicial+(valor)
                + con.guardarnumero((txtentrada.getText())))
                - (con.guardarnumero((txtsalida.getText())));
        return montototal;
    }

    private void txtcajainicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcajainicialFocusLost
        /*
        p_control con = p_control.getInstancia();
        float montototal = 0f;
        try {
            montototal = devuelvemontototal();
            txttotal.setText(con.mostrarnumero(montototal));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        */
    }//GEN-LAST:event_txtcajainicialFocusLost

    private void txtcajainicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcajainicialKeyPressed

    }//GEN-LAST:event_txtcajainicialKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        p_control con = p_control.getInstancia();
        
        try {
            montototal = devuelvemontototal();
            txttotal.setText(con.mostrarnumero(montototal));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    Float totalentradatipopagohoy() {
        d_movimiento mov = new d_movimiento();
        Float total = 0f;

        try {
            //EN UN FUTURO PUEDE SER OTRO TIPO DE PAGO, EJ.: CAJA
            total = mov.totalentradatipopagohoy("CAJA");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return total;
    }

    Float totalsalidatipopagohoy() {
        d_movimiento mov = new d_movimiento();
        Float total = 0f;

        try {
            //EN UN FUTURO PUEDE SER OTRO TIPO DE PAGO, EJ.: CAJA
            total = mov.totalsalidatipopagohoy("CAJA");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return total;
    }

    /*Float totalcajainicial() {
        Float totalentrada = 0f;
        Float totalsalida = 0f;
        Float total = 0f;
        
        try {
            totalentrada = totalentradatipopagohoy();
            totalsalida = totalsalidatipopagohoy();
            total = totalentrada - totalsalida;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return total;
    }*/
    Date parsefechadate(Date fecha) throws Exception {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;

        try {
            String nuevafecha = formato.format(fecha);
            fechaDate = formato.parse(nuevafecha);
        } catch (Exception ex) {
            throw new Exception(ex.getMessage());
        }
        return fechaDate;
    }

    String parsefechastring(java.util.Date fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String fechastr = formato.format(fecha);

        return fechastr;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                p_caja dialog = new p_caja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdcfecha;
    private javax.swing.JLabel lbldatoscaja;
    private javax.swing.JTextField txtcajainicial;
    private javax.swing.JTextField txtentrada;
    private javax.swing.JTextField txtsalida;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables

}
