/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.paneles;

import dominio.d_cfe;
import dominio.d_generarcfe;
import dominio.d_movimiento;
import dominio.d_parametro;
import dominio.d_parametroscfe;
import java.awt.Dimension;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.datacontract.schemas._2004._07.sicfecontract.SICFERespuestaEnvioCFE;
import persistencia.p_conexion;

/**
 *
 * @author Gonzalo
 */
public class p_resguardo extends javax.swing.JDialog implements Serializable, FocusListener {

    p_control con = p_control.getInstancia();

    /**
     * Creates new form p_fichainquilino
     */
    public p_resguardo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtimporte.addFocusListener(this);
        cargarfecha();
    }

    void cargarfecha() {
        jdcfecha.setDateFormatString("dd/MM/yyyy");
        jdcfecha.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtimporte = new javax.swing.JTextField();
        txtci = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jdcfecha = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txtpesos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        eticket = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txttotal_mas_iva = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtconcepto = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtadenda = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        prueba = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMITIR TICKET");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.red);
        jLabel10.setText("(*) DATOS OBLIGATORIOS PARA DGI (E-TICKET)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 500, 340, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("FECHA (*)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 20, 100, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("CONCEPTO (*)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 220, 120, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE (*)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 17);

        txtimporte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtimporte.setPreferredSize(new java.awt.Dimension(6, 40));
        txtimporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimporteKeyTyped(evt);
            }
        });
        getContentPane().add(txtimporte);
        txtimporte.setBounds(10, 370, 150, 30);

        txtci.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtci.setPreferredSize(new java.awt.Dimension(6, 40));
        getContentPane().add(txtci);
        txtci.setBounds(10, 190, 230, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 460, 470, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("CI (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 90, 17);

        txtnombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtnombre.setPreferredSize(new java.awt.Dimension(6, 40));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
        });
        getContentPane().add(txtnombre);
        txtnombre.setBounds(10, 90, 230, 30);

        jdcfecha.setDateFormatString("dd/MM/yyyy");
        jdcfecha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        getContentPane().add(jdcfecha);
        jdcfecha.setBounds(10, 40, 230, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("DESCRIPCION DEL MONTO");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 300, 230, 17);

        txtpesos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtpesos.setPreferredSize(new java.awt.Dimension(6, 40));
        getContentPane().add(txtpesos);
        txtpesos.setBounds(10, 320, 470, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("DIRECCION (*)");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 120, 100, 17);

        txtdireccion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtdireccion.setPreferredSize(new java.awt.Dimension(6, 40));
        getContentPane().add(txtdireccion);
        txtdireccion.setBounds(10, 140, 230, 30);

        eticket.setText("DGI (E-TICKET)");
        eticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eticketMouseClicked(evt);
            }
        });
        getContentPane().add(eticket);
        eticket.setBounds(10, 430, 120, 23);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("TOTAL + IVA ($):");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 350, 150, 17);

        txttotal_mas_iva.setEditable(false);
        txttotal_mas_iva.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txttotal_mas_iva);
        txttotal_mas_iva.setBounds(170, 370, 150, 30);

        txtconcepto.setColumns(20);
        txtconcepto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtconcepto.setLineWrap(true);
        txtconcepto.setRows(5);
        txtconcepto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtconcepto.setPreferredSize(new java.awt.Dimension(230, 74));
        jScrollPane2.setViewportView(txtconcepto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 230, 50);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("ADENDA (*)");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 220, 120, 17);

        txtadenda.setColumns(20);
        txtadenda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtadenda.setLineWrap(true);
        txtadenda.setRows(5);
        txtadenda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtadenda.setPreferredSize(new java.awt.Dimension(230, 74));
        jScrollPane3.setViewportView(txtadenda);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(250, 240, 230, 50);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("TIPO DE DOCUMENTO");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 410, 170, 17);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("TOTAL SIN IVA (*)");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 350, 150, 17);

        prueba.setText("PRUEBA (E-TICKET)");
        prueba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pruebaMouseClicked(evt);
            }
        });
        getContentPane().add(prueba);
        prueba.setBounds(140, 430, 190, 23);

        setBounds(0, 0, 504, 566);
    }// </editor-fold>//GEN-END:initComponents

    Float devuelveiva(Float importe) throws Exception { //recibe comision
        d_parametro par = new d_parametro();
        Float iva = 0.0F;

        par = par.buscarparametro();

        iva = importe * par.getIva() / 100;

        return iva;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //inq.setInq_fechaic(parsefechadate(jdcfechaic.getDate()));
            int ax = JOptionPane.showConfirmDialog(null, toUpperCase("¿desea generar documento?"), "CONFIRMACION", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ax == JOptionPane.YES_OPTION) {
                if (eticket.isSelected()) {
                    //VA A GENERAR UN E-TICKET
                    generare_ticket();
                    return;
                    //generarreporte_eticket(id);
                }
                if (prueba.isSelected()) {
                    generare_ticket_prueba();
                } 
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void generare_ticket_prueba() throws Exception {
        java.sql.Connection c;
        p_conexion conex = p_conexion.getInstancia();
        c = conex.crearconexion();
        Float importe, iva;

        String template = "reporte-factura_1.jasper";
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObject(template);

        Map param = new HashMap();
        //120196190011
        param.put("ruc", txtci.getText());
        param.put("tipo_cfe", "e-Ticket");
        param.put("cliente", txtnombre.getText());
        param.put("domicilio_fiscal", txtdireccion.getText());
        param.put("concepto", txtconcepto.getText());

        importe = con.guardarnumero(txtimporte.getText());

        iva = devuelveiva(importe);
        param.put("total", con.mostrarnumero(importe + iva));
        param.put("subtotal", con.mostrarnumero(importe));
        param.put("adenda", txtadenda.getText());
        param.put("iva", con.mostrarnumero(iva));
        JasperPrint jasperprint = JasperFillManager.fillReport(reporte, param, c);
        JasperExportManager.exportReportToPdfFile(jasperprint, "prueba_doc_" + txtci.getText() + ".pdf");
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "prueba_doc_" + txtci.getText() + ".pdf");
    }

    void generare_ticket() throws Exception {
        d_parametroscfe pcfe = new d_parametroscfe();
        String nombre, ci, direccion, concepto, adenda;
        Float importe, iva;
        Date fecha;
        int id_generado = -1;

        pcfe = pcfe.buscarparametroscfe();
        if (pcfe == null) {
            throw new Exception("debe ingresar parametros cfe: nombre, clave y tenant");
        }
        //controlar_campos();
        nombre = txtnombre.getText();
        ci = txtci.getText();
        direccion = txtdireccion.getText();
        concepto = txtconcepto.getText();
        adenda = txtadenda.getText();
        importe = con.guardarnumero(txtimporte.getText());
        //comision = con.guardarnumero(txtcomision.getText());
        iva = devuelveiva(importe);
        //txtiva.setText(con.mostrarnumero(iva));
        txttotal_mas_iva.setText(con.mostrarnumero(importe + iva));
        fecha = fechaactual();
        String mensaje = "NOMBRE: " + nombre + "\n"
                + "CI: " + ci + "\n"
                + "DIRECCION: " + direccion + "\n"
                + "CONCEPTO: " + concepto + "\n"
                + "TOTAL (+ IVA) $: " + con.mostrarnumero(importe + iva) + "\n"
                + "ADENDA: " + adenda + "\n";
        int ax = JOptionPane.showConfirmDialog(null, devuelvescrollpregunta(mensaje), "¿DESEA ENVIAR A DGI EL E-TICKET CON LOS SIGUIENTES DATOS?\n", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (ax == JOptionPane.YES_OPTION) {
            /*
            d_movimiento mov = new d_movimiento();
            Float total_mas_iva = importe + iva;
            mov.setProp_id(0);
            mov.setInq_casa(0);
            mov.setMqp(0);
            mov.setAqp(0);
            mov.setDetalle(concepto);
            mov.setEntrada(total_mas_iva);
            mov.setSalida(0f);
            mov.setComision(comision);
            mov.setIva(iva);
            mov.setIrpf(0f);
            mov.setFecha(fecha);
            mov.setIrpftipo("");
            mov.setTipo("");//ACA SE AGREGA Nº Y SERIE E-TICKET
            mov.setTipopago("");
            id_generado = mov.guardarmovimientoe_ticket(mov);
             */
            //con.escribirfichero("INMO - se ingresa e-ticket inmo, id: " + id_generado + " concepto: " + mov.getDetalle() + " -- " + "salida: " + con.mostrarnumero(mov.getSalida()));
            adenda = adenda + "\n"
                    + " - ID TRANSACC.: " + id_generado;
            //id_generado = (con.obtenerMayorNumDOCCFE(101) + 1);
            int id = ((con.maximo_mov() + 1) * 100);
            envio_dgi(id, nombre, ci, direccion, concepto, importe, iva, adenda, fecha);
        }
    }

    void controlar_campos() throws Exception {
        if (txtnombre.getText().equals("")) {
            throw new Exception("el nombre no puede estar vacío");
        }
        if (txtci.getText().equals("")) {
            throw new Exception("la ci no puede estar vacía");
        }
        if (txtdireccion.getText().equals("")) {
            throw new Exception("la dirección no puede estar vacía");
        }
        if (txtimporte.getText().equals("") || Float.parseFloat(txtimporte.getText()) <= 0) {
            throw new Exception("el importe no puede estar vacío o ser menor igual a 0");
        }
        //if (txtcomision.getText().equals("") || Float.parseFloat(txtimporte.getText()) < 0) {
        //throw new Exception("la comisión no puede estar vacía o ser menor a 0");
        //}
        if (txtadenda.getText().equals("")) {
            throw new Exception("la adenda no puede estar vacía");
        }
    }

    Date fechaactual() throws Exception {
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy", new Locale("es_ES"));
        String fechastr = (formateador.format(new Date()));

        return parsefechadate(fechastr);
    }

    Date parsefechadate(String fecha) throws Exception {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;

        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            throw new Exception("revise formato de año");
        }
        return fechaDate;
    }

    JScrollPane devuelvescrollpregunta(String mensaje) {
        JTextArea textArea = new JTextArea(mensaje);
        JScrollPane scrollPane = new JScrollPane(textArea);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setEditable(false);
        scrollPane.setPreferredSize(new Dimension(500, 250));
        return scrollPane;
    }

    void envio_dgi(int id_mov, String nombre, String ci, String direccion, String concepto, Float total_recibido, Float iva_recibido, String adenda, Date fecha_recibida) throws Exception {
        //primero chequear que id mov no este en la nueva tabla que guarda cfe
        d_cfe cfe = new d_cfe();
        d_parametroscfe pcfe = new d_parametroscfe();
        SICFERespuestaEnvioCFE envio = new SICFERespuestaEnvioCFE();
        d_generarcfe gt = new d_generarcfe();
        Integer i = -1;
        d_movimiento m = new d_movimiento();

        pcfe = pcfe.buscarparametroscfe();
        if (pcfe == null) {
            throw new Exception("debe ingresar parametros cfe: nombre, clave y tenant");
        }

        gt = gt.ticketdefecto();
        //ver si es necesario cambiar alguna variable de ticket por defecto
        gt.setCfexml(gt.cfexmlticket_emitida(nombre, ci, direccion, concepto, total_recibido, iva_recibido, adenda, fecha_recibida));
        //gt.setReferenciaERP("56555");
        gt.setNomusuario(pcfe.getNomusuario());
        gt.setClave(pcfe.getClave());
        gt.setTenant(pcfe.getTenant());

        //int id = (con.obtenerMayorNumDOCCFE(101) + 1);//e-ticket 101
        gt.setReferenciaERP(String.valueOf(id_mov));

        envio = envioCFE(gt.getNomusuario(), gt.getClave(),
                gt.getTenant(), gt.getCliente(), gt.getCfexml(), gt.getReferenciaERP(),
                gt.getReferenciaERP2(), gt.getDevolverQR(), gt.getSizeQR(),
                gt.getImprime(), gt.getRecurso(), gt.getTemplate(), gt.getDevolverXML(),
                gt.getErpPideValidacion(), gt.getVersion());
        //i = envio.getCodigo(); 4547800
        if (envio.getCodigo() != 0) {
            while (envio.getCodigo() == 100009) {
                id_mov = id_mov + 1;
                gt.setReferenciaERP(String.valueOf(id_mov));
                envio = envioCFE(gt.getNomusuario(), gt.getClave(),
                        gt.getTenant(), gt.getCliente(), gt.getCfexml(), gt.getReferenciaERP(),
                        gt.getReferenciaERP2(), gt.getDevolverQR(), gt.getSizeQR(),
                        gt.getImprime(), gt.getRecurso(), gt.getTemplate(), gt.getDevolverXML(),
                        gt.getErpPideValidacion(), gt.getVersion());
                if (envio.getCodigo() == 0) {
                    id_mov = (con.minimo_entre_cfe_y_mov() - 1);//CHEQUEAR ESTO PORQUE EL MINIMO EN TABLA CFE PUEDE EXISTIR EN MOVIMIENTOS Y VICEVERSA
                    //id_mov = (cfe.minimoid() - 1);//ID MOVIMIENTO
                    guardarcfe(ci, nombre, id_mov, "A", envio.getIdCFE().getValue().getNumero(),
                            envio.getIdCFE().getValue().getRucemisor().getValue(),
                            envio.getIdCFE().getValue().getTipo(), envio.getIdCFE().getValue().getObservado());
                    break;
                }
            }
            //if (envio.getCodigo() == 100009) {
            //throw new Exception(envio.getDescripcion().getValue());
            //}
        } else {
            id_mov = (con.minimo_entre_cfe_y_mov() - 1);//CHEQUEAR ESTO PORQUE EL MINIMO EN TABLA CFE PUEDE EXISTIR EN MOVIMIENTOS Y VICEVERSA
            //id_mov = (cfe.minimoid() - 1);//ID MOVIMIENTO
            guardarcfe(ci, nombre, id_mov, "A", envio.getIdCFE().getValue().getNumero(),
                    envio.getIdCFE().getValue().getRucemisor().getValue(),
                    envio.getIdCFE().getValue().getTipo(), envio.getIdCFE().getValue().getObservado());
            //int numserie=envio.getIdCFE().getValue().getNumero();
            //throw new Exception(envio.getDescripcion().getValue());
            //JOptionPane.showMessageDialog(null,numserie);  
        }

        JOptionPane.showMessageDialog(this, "E-TICKET GENERADO CORRECTAMENTE, MOVIMIENTO Nº: " + id_mov, "AVISO", JOptionPane.INFORMATION_MESSAGE);
    }

    private static SICFERespuestaEnvioCFE envioCFE(java.lang.String nomusuario, java.lang.String clave,
            java.lang.String tenant, java.lang.String cliente, java.lang.String cfexml, java.lang.String referenciaERP,
            java.lang.String referenciaERP2, java.lang.Boolean devolverQR, java.lang.Integer sizeQR,
            java.lang.Integer imprime, java.lang.String recurso, java.lang.String template, java.lang.Boolean devolverXML,
            java.lang.Boolean erpPideValidacion, java.lang.String version) {
        org.tempuri.ImpSICFEEmisor service = new org.tempuri.ImpSICFEEmisor();
        org.tempuri.ISICFEEmisor port = service.getBasicHttpBindingISICFEEmisor();
        return port.envioCFE(nomusuario, clave, tenant, cliente, cfexml, referenciaERP, referenciaERP2,
                devolverQR, sizeQR, imprime, recurso, template, devolverXML, erpPideValidacion, version);
    }

    void guardarcfe(String ci, String nombre_cliente, Integer idmov, String serie, Integer numero, String rucemisor, Integer tipo, Integer observado) throws Exception {
        d_cfe cfe = new d_cfe();

        cfe.setIdmov(idmov);
        cfe.setSerie(serie);
        cfe.setNumero(numero);
        cfe.setRucemisor(rucemisor);
        cfe.setTipo(tipo);
        cfe.setObservado(observado);

        cfe.guardarcfe(cfe);
        con.escribirfichero("se emite e-ticket dgi, a nombre de " + nombre_cliente + " movimiento: " + idmov + " -- serie: " + serie + " -- numero: " + numero + " -- ruc emisor: " + rucemisor + " -- tipo: " + tipo + " -- observado: " + observado);
        actualizaridmov(idmov, serie, numero, tipo);
    }

    void actualizaridmov(Integer idmov, String serie, Integer numero, Integer tipo) throws Exception {
        d_movimiento mov = new d_movimiento();

        String detalle = String.valueOf(tipo) + "_" + serie + "_" + String.valueOf(numero);
        mov.actualizartipomov(idmov, detalle);
        con.escribirfichero("INMO - se actualiza en tabla movimientos, id: " + idmov + " tipo: " + detalle);
    }




    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed

    }//GEN-LAST:event_txtnombreKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void eticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eticketMouseClicked
        if (eticket.isSelected()) {
            prueba.setEnabled(false);
            prueba.setSelected(false);
        } else {
            prueba.setEnabled(true);
            prueba.setSelected(false);
        }
    }//GEN-LAST:event_eticketMouseClicked

    private void txtimporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimporteKeyTyped
        char car = evt.getKeyChar();
        if (!Character.isDigit(car)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtimporteKeyTyped

    private void pruebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pruebaMouseClicked
        if (prueba.isSelected()) {
            eticket.setEnabled(false);
            eticket.setSelected(false);
        } else {
            eticket.setEnabled(true);
            eticket.setSelected(false);
        }
    }//GEN-LAST:event_pruebaMouseClicked


    void generarreporte_eticket(int id) throws Exception {
        java.sql.Connection c;
        p_conexion conex = p_conexion.getInstancia();
        c = conex.crearconexion();

        String template = "recibo-eticket.jasper";
        JasperReport reporte = null;
        reporte = (JasperReport) JRLoader.loadObject(template);

        Map param = new HashMap();

        float num = con.guardarnumero(txttotal_mas_iva.getText());
        String importe = con.mostrarnumero(num);
        param.put("fecha", parsefechadate(jdcfecha.getDate()));
        param.put("nombre", txtnombre.getText());
        param.put("ci", txtci.getText());
        param.put("direccion", txtdireccion.getText());
        param.put("texto", txtconcepto.getText());
        //param.put("adenda", txtadenda.getText() + " - ID TRANSACC.: " + id);
        param.put("movimiento", "entrada");
        param.put("pesos", txtpesos.getText() + "\n" + "$ " + importe);
        JasperPrint jasperprint = JasperFillManager.fillReport(reporte, param, c);
        JasperViewer visor = new JasperViewer(jasperprint, false);
        visor.setTitle("Recibo Resguardo");
        visor.setVisible(true);
        this.dispose();
    }

    Date parsefechadate(Date fecha) throws Exception {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;

        try {
            String nuevafecha = formato.format(fecha);
            fechaDate = formato.parse(nuevafecha);
        } catch (Exception ex) {
            throw new Exception(ex.getMessage());
        }
        return fechaDate;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_resguardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_resguardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_resguardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_resguardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                p_resguardo dialog = new p_resguardo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox eticket;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcfecha;
    private javax.swing.JCheckBox prueba;
    private javax.swing.JTextArea txtadenda;
    private javax.swing.JTextField txtci;
    private javax.swing.JTextArea txtconcepto;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtimporte;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpesos;
    private javax.swing.JTextField txttotal_mas_iva;
    // End of variables declaration//GEN-END:variables
  @Override
    public void focusGained(FocusEvent e) {
        //ENTRA A CAJA DE TEXTO
        if (e.getSource() == txtimporte) {
            //ENTRO A CAJA IMPORTE

        }
    }

    @Override
    public void focusLost(FocusEvent e) {
        //SALE DE CAJA DE TEXTO
        if (e.getSource() == txtimporte) {
            //SALIO DE IMPORTE, LLAMAR FUNCION CALCULAR_IVA
            try {
                if (txtimporte.getText().equals("")) {
                    return;
                }
                Float importe = con.guardarnumero(txtimporte.getText());
                Float iva = devuelveiva(importe);
                //txtiva.setText(con.mostrarnumero(iva));
                txttotal_mas_iva.setText(con.mostrarnumero(importe + iva));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, toUpperCase(ex.getMessage()), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
